name: Deploy Zola to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# 👇 THIS is the bit you were missing
permissions:
  contents: write   # allow pushing to gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (incl. submodules if you use a theme)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build & Deploy
        uses: shalzz/zola-deploy-action@master
        env:
          PAGES_BRANCH: gh-pages
          TOKEN: ${{ secrets.GITHUB_TOKEN }}   # built-in token, now with write perms
          # BUILD_FLAGS: --force               # optional
          # CUSTOM_DOMAIN: elvim.cc            # optional; or keep a /static/CNAME file
