name: Deploy Zola to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (incl. submodules if you use a theme)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build & Deploy
        uses: shalzz/zola-deploy-action@master
        env:
          # Target branch for Pages
          PAGES_BRANCH: gh-pages

          # Use GitHub's built-in token; no PAT needed
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # Optional: if you have a custom domain, keep a CNAME file in /static
          # The action will copy it into /public automatically.
          # CUSTOM_DOMAIN: elvim.cc

          # Optional build flags (e.g., --force)
          # BUILD_FLAGS: --force
