# .github/workflows/gh-pages.yml
name: Build and deploy Zola site

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build site
        run: zola build

      - name: deploy to GitHub Pages
        uses: shalzz/zola-deploy-action@master
        env:
          PAGES_BRANCH: gh-pages
          TOKEN: ${{ secrets.ZOLAKEY }}

